### ISSUE TITLE
How would i send the ffmpeg output to 3LAS running on a remote server?

### ISSUE THREAD

**Issue by zyphersworld** [JoJoBond/3LAS#2]
You have done an Awesome job! I was trying to think of how i was going to implement something like this. thanks a million. Now my question is, How would i send the ffmpeg output to 3LAS running on a remote server? you see i want to let the users use their own internet connection and not Wi-Fi to connect to the stream. but the stream should be sent from the recording computer to a remote server running 3LAS.
At the moment i'm using butt (broadcast using this tool) to record and stream the feed to an icecast server. the lag is ok for non-realtime application but for use with translation it is unacceptable. Your tool works great for this. but i am not sure how to pipe the output of ffmpeg to my google cloud vm instance. thanks again and any help on this matter would be greatly appreciated. Cheers.

**Comment by JoJoBond** [comment]
Are you going to have a limit number of users?
If so, you could try to use ffmpeg with tcp connections and SSH tunnels.
I'm doing something similar in another project.
Basically what I do is this:
Local FFmpeg encoding -> SSH Tunnel to server -> Server side remultiplex -> RTMP

That could be easily adapted to just pipe the data to 3LAS.
However, every user would need SSH credentials which might not be an ideal solution for user you don't trust.

You could also implement a small server in node.js or java (etc.) that does the login and afterwards just pipes the data to a 3LAS instance.

It really depends on your needs.

**Comment by martinseiter** [comment]
Hi JoJoBond, 
is it possible to send an Audio RTMP Stream directly to the server? if yes -how? rtmp://server/path
what else is needed on server to pipe that to 3LAS?
yours M

**Comment by JoJoBond** [comment]
Check you the rtmp plugin for nginx: https://github.com/arut/nginx-rtmp-module
You can configure it to run an external command whenever an incomming stream starts: https://github.com/arut/nginx-rtmp-module/wiki/Directives#exec_push

You can use this to retransmits an incoming stream via 3LAS.

**Comment by martinseiter** [comment]
may i ask you to outline how to get your code running, i would lie to use it as a silent disco for my friends.
yours Martin.

**Comment by JoJoBond** [comment]
As far as I understand it, you'd like to do the following, correct?

Audio -[RTMP]-> RTMP Server -[3LAS]-> Smartphone

Is that correct?

**Comment by martinseiter** [comment]
Yes, but I can also use the local audio in

**Comment by JoJoBond** [comment]
The hardware audio jack on the server?

**Comment by martinseiter** [comment]
Yes that might be an option - or another pc.

**Comment by JoJoBond** [comment]
Is low latency such an important aspect for your application? If not, Shoutcast/Icecast would do just fine.

**Comment by martinseiter** [comment]
yes, latency is an important factor, people should have the same rhythm feeling.


________________________________
 
DI Martin SEITER
CEO

3DHD
Flötzersteig 164   A-1140 Wien

Tel.: +43 1 912 38 36
Mobil: +43 699 100 50 410
 
E-Mail: m.seiter@3dhd.at
Web: www.3dhd.at  /  www.martinseiter.com

**Comment by JoJoBond** [comment]
For the most basic application you will need:
A webserver.
A node.js installation on the webserver.
A ffmpeg installation on the webserver.

You copy the contents of the client folder to the webservers root folder.
You copy the contents of the server folder somewhere else one the webserver.
You run one of the demo scripts e.g. livemp3.sh.
You connect to your webserver via a webbrowser and start listening.
