### ISSUE TITLE
Very light 'tic' sound in high frequencies only on PC

### ISSUE THREAD

**Issue by cemkoker** [JoJoBond/3LAS#20]
I don't know why but my previous issue seems to have been deleted :(

Anyway posting back. I have noticed that when using mp3, I clearly hear a kind of very light noise (similar to hearing an old vinyl). It is very clear on PC but on Mac I don't hear it. 

Can this be something related to the audio decoding on Windows ?

**Comment by JoJoBond** [comment]
That's typically from the 'edges' of two decode windows. You could try to raise the value of `settings["mpeg"]["MinDecodeFrames"]`, that could improve it a bit. Not much I can do about it, as it seems to be browser specific. You could also try different browsers.

**Comment by JoJoBond** [comment]
Closed due to usage of now deprecated feature.
