### ISSUE TITLE
Usable on Raspberry Pico

### ISSUE THREAD

**Issue by jgourinda** [JoJoBond/3LAS#21]
Hello, 

I am fairly new to micro controllers but I have a project where I would like to live stream the audio signal of a microphone using a Raspberry Pico connected to the internet. For each connected microphone I can expect to have many thousand clients that need to hear the audio with latency below 1 second. 
Do you think that it is achievable using 3LAS and does it work on Raspberry Pico for example ?

**Comment by JoJoBond** [comment]
A Raspberry Pi Pico will not work since it won't run Linux. You'll need at the very least something like a Raspberry Pi Zero 2 W or OrangePi Zero2, probably even something better. I'd don't know how good WebRTC scales with >100 clients, you'd have to test that. If you want to run multiple different streams from one machine the load will also add up. I have tested 16 streams on an older Xeon running at about 2.6GHz using about 40% CPU. CPU load should be fairly stable over time. First connections can give small peaks in CPU load.

**Comment by jgourinda** [comment]
Thank you for reply ! 

I apologize if what follows is naive. I come from a web development world. 

Could you explain what stops something as simple as what I have in mind to work ? 

The microphone signal is bottom line voltage that varies over time. Depending on how often I sample I get n point per unit of time. 
What stops the Pico from continuously sending these n point per unit of time to a central server with decent capabilities something like Compute optimized instances on AWS. 
Then my more > thousand clients connect to that proper server in order to get these n points per unit of time with as low as possible latency and play the audio sound ?

**Comment by JoJoBond** [comment]
Don't worry :) I try my best to clarify things.

I get about 0.5 second latency on in an Wireless LAN environment (not data over Internet).
To achieve latency below 1 second over the internet, a cloud computing approach is IMO not feasible.
If you want to use 3LAS, you'll need to stream on site and with capable hardware, plus you'll need an internet connection that can handle the bandwidth for all clients. 3LAS is designed for on site installations like convention centres (e.g. translation) or silent disco type of scenarios or small scale internet transmissions (e.g. remote controlled radio tuner).
Your conditions (1000+ clients, < 1sec latency, over internet) make 3LAS hard to implement without proper hardware and bandwidth.
Depending on what you are willing to do on your receiver devices you have other options though. But if you want to be HTML5 based you are limited to wav/mp3 over WebSocket or WebRTC. Long-polling icecast servers or even using HLS will give you at least 5 sec latency.
If HTML5 is not a must you could simply use RTSP or RTMP streams over a central server.

**Comment by jgourinda** [comment]
Thank you very much for the detailed response ! 
Much appreciated !
