### ISSUE TITLE
Adding a small buffer to reduce choppy audio?

### ISSUE THREAD

**Issue by BellesoftConsulting** [JoJoBond/3LAS#3]
Hi there,
1st of all great project! works great! except if there are brief network packet losses for a client. Where would I look to add some sort of small buffer (1 second for example) to reduce choppy audio??

**Comment by sreplans** [comment]
I was thinking something client side...

**Comment by JoJoBond** [comment]
Hi,

3LAS uses Websockets which themself run over TCP/IP, so packetloss should be handelt automaticaly.
However, if loss occurs, there will be a brief period of lagg were the server will resend the lost packets.
If you wish to increase the buffer size, you can do so by increasing the 'StartOffset' in'audio_player.js'.
This value defines how many seconds (from the decoding of the first packets) in the future the playback will start.
