### ISSUE TITLE
iOS 11 no sound

### ISSUE THREAD

**Issue by int32at** [JoJoBond/3LAS#9]
Hey there,

first of thanks for providing such a cool tool. Have been playing around with it a lot and it works amazingly well, except on iOS 11 (i'm using 11.02 on an iPhone 7). I hit the play button on my dev iPhone but i'm not able to hear any audio. The event log seems fine, tested in both Chrome and Safari.

> [21:51:27] Detected: iOS, Chrome
[21:51:27] Using MIME: audio/mpeg on port: 9601
[21:51:27] Init of HTMLPlayerControls succeeded
[21:51:27] Init of PCMAudioPlayer succeeded
[21:51:27] Init of AudioFormatReader succeeded
[21:51:29] Init of WebSocketClient succeeded
[21:51:29] Trying to connect to server.
[21:51:29] Established connection with server.

Any clue how to solve this issue? Any help is very much appreciated!

**Comment by int32at** [comment]
haha not even a minute after posting i was able to "solve" this issue.... it appears that, even though the volume was turned up to the max. level, you now have to turn the mute switch from silent to ringer. see here https://www.tenorshare.com/ios-11/how-to-fix-iphone-no-sound-issue-after-ios-11-upgrade.html

**Comment by JoJoBond** [comment]
Thank you for the information. If you encounter any other problem, don't hesitate to ask.
